name: Test Build Number
on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}  
    # bump version
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: "1.0.${{ steps.bump_version.outputs.next-version }}"
        version-fragment: 'alpha'
    - run: echo "Build apk to release with Build Version ${{ steps.bump_version.outputs.next-version }} > Build number ${{ steps.buildnumber.outputs.build_number }}"
